---
baseURL: ""

canonifyURLs: true
enableGitInfo: true
enableRobotsTXT: true

languageCode: en-us
title: "Minimal"
copyright: ""

params:
  description: "Minimal template for Hugo"

  social:
    - name: GitHub
      description: "Project page on GitHub"
      url: "https://github.com"
      icon: github
