name: Format Code with Prettier 

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 2

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_plugins: prettier-plugin-go-template
          prettier_options: --write **/*.{js,css,scss,html,json,yml,md}
          only_changed: True  
